### ISSUE TITLE
The Ghost won't get off of me

### ISSUE THREAD

**Issue by Coolandon77** [00-Evan/shattered-pixel-dungeon-gdx#18]
On Level 4 in Sewers the Sad Ghost is occupying the same space as the hero after I defeated the Great Crab.  Leaving the level did not work.  When I came back to level 4 the Ghost was back.  Also using a fade leaf worked briefly but the Ghost was back in the hero's square before it was possible to speak with the ghost to receive the weapon or armor.  I am using the newly released beta of v0.4.2-Beta-1.  Thank you

**Comment by 00-Evan** [comment]
firstly, this is the source for the GDX desktop port, this issue is not present in this version
secondly, beta issues have no relation to the open soruce, as beta releases do not have their source released.

If you encounter issues with betas, please contact me directly rather than posting source issues. Also, beta-2 is out which fixes this issue.

**Comment by Coolandon77** [comment]
Excellent.  Sorry, I just started using the Beta's and didn't know where to go with issues.  Thank you for your quick reply and for the correction of what I should do next time.  Also thank you for a wonderful game.
