### ISSUE TITLE
New camera movement issue

### ISSUE THREAD

**Issue by internecivusraptus** [00-Evan/shattered-pixel-dungeon-gdx#42]
The dungeon map in a desktop version (v0.7.5a) shakes uncontrollably after each move unless I zoom in/zoom out. 

0.7.4c didn't have such glitches, so I guess this may be connected with a new smooth camera.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this, can you let me know what resolution your using, perhaps include a screenshot or a video?

**Comment by internecivusraptus** [comment]
After a fresh reboot it seemed to disappear, but now after a few days of uptime it returned. I blame my shitty videocard, nevertheless here is the video in fullscreen.
[output-smaller-2.mkv.gz](https://github.com/00-Evan/shattered-pixel-dungeon-gdx/files/3722961/output-smaller-2.mkv.gz)

**Comment by 00-Evan** [comment]
Looks like the issue is caused by exceptionally low framerate. I just tested the game with limited FPS and was getting camera oddness at around 15 FPS. It makes the game unplayable once FPS goes below about 8.

This isn't an issue that's exclusive to the desktop version, so I'm going to move it over to the main repository. Issue here: https://github.com/00-Evan/shattered-pixel-dungeon/issues/350
